language: java

sudo: false
 
services:
    - docker
    
script:
    - sudo docker run -it -v $(pwd):/usr/src/mymaven  maven:3.3-jdk-8  bash -c "cd /usr/src/mymaven; mvn test;"
    # Above command pulls the MVN image and runs the tests